import type { RuntimeCapsuleManifest } from '../../contracts/runtimeCapsule';

export const DEFAULT_RUNTIME_CAPSULE_MANIFESTS: RuntimeCapsuleManifest[] = [
  {
    id: 'audio.shell',
    kind: 'audio',
    memoryTier: 'light',
    startup: 'core',
    backgroundPolicy: 'while-active',
    warmRetentionMs: 30_000,
    hibernateAfterMs: 120_000,
    provides: ['audio.shell'],
  },
  {
    id: 'audio.transport',
    kind: 'audio',
    memoryTier: 'medium',
    startup: 'first-use',
    backgroundPolicy: 'realtime-critical',
    warmRetentionMs: 60_000,
    hibernateAfterMs: 300_000,
    dependencies: ['audio.shell'],
    provides: ['audio.transport', 'audio.queue'],
  },
  {
    id: 'music-library.query',
    kind: 'music-library',
    memoryTier: 'heavy',
    startup: 'first-use',
    backgroundPolicy: 'while-active',
    warmRetentionMs: 20_000,
    hibernateAfterMs: 90_000,
    provides: ['music-library.query', 'music-library.cover'],
  },
  {
    id: 'audio.dsp-vst',
    kind: 'audio',
    memoryTier: 'heavy',
    startup: 'first-use',
    backgroundPolicy: 'while-active',
    warmRetentionMs: 10_000,
    hibernateAfterMs: 60_000,
    dependencies: ['audio.transport'],
    provides: ['audio.dsp-vst', 'vst.manager'],
  },
  {
    id: 'audio.visualizer',
    kind: 'visualizer',
    memoryTier: 'medium',
    startup: 'active-space',
    backgroundPolicy: 'while-visible',
    warmRetentionMs: 8_000,
    hibernateAfterMs: 30_000,
    dependencies: ['audio.transport'],
    provides: ['audio.visualizer.spectrum'],
  },
  {
    id: 'visual.canvas.pixi',
    kind: 'visualizer',
    memoryTier: 'heavy',
    startup: 'active-space',
    backgroundPolicy: 'while-visible',
    warmRetentionMs: 8_000,
    hibernateAfterMs: 30_000,
    provides: ['visual.canvas.pixi'],
  },
  {
    id: 'debug.process-perf',
    kind: 'debug',
    memoryTier: 'medium',
    startup: 'manual',
    backgroundPolicy: 'while-active',
    warmRetentionMs: 5_000,
    hibernateAfterMs: 20_000,
    provides: ['debug.process-perf'],
  },
  {
    id: 'ornaments.render-overlay',
    kind: 'ornaments',
    memoryTier: 'medium',
    startup: 'first-use',
    backgroundPolicy: 'while-visible',
    warmRetentionMs: 8_000,
    hibernateAfterMs: 30_000,
    provides: ['ornaments.render-overlay'],
  },
  {
    id: 'platform.workspace',
    kind: 'platform',
    memoryTier: 'heavy',
    startup: 'active-space',
    backgroundPolicy: 'while-active',
    warmRetentionMs: 10_000,
    hibernateAfterMs: 60_000,
    provides: ['platform.workspace'],
  },
  {
    id: 'plugin.runtime',
    kind: 'plugin',
    memoryTier: 'heavy',
    startup: 'first-use',
    backgroundPolicy: 'while-active',
    warmRetentionMs: 10_000,
    hibernateAfterMs: 60_000,
    provides: ['plugin.runtime'],
  },
  {
    id: 'editor.tools',
    kind: 'editor',
    memoryTier: 'heavy',
    startup: 'manual',
    backgroundPolicy: 'while-active',
    warmRetentionMs: 10_000,
    hibernateAfterMs: 60_000,
    provides: ['editor.tools'],
  },
];
