export {
  BILIBILI_CONNECTOR_ID,
  NETEASE_CONNECTOR_ID,
  normalizePlatformConnectorId,
  resolvePlatformConnectorTemplate,
  type BuiltinPlatformCompatRegistration,
  type PlatformConnectorAdapter,
  type PlatformConnectorAuthSnapshot,
  type PlatformConnectorAuthState,
  type PlatformConnectorAvailability,
  type PlatformConnectorDefinition,
  type PlatformConnectorId,
  type PlatformConnectorTemplate,
  type PlatformConnectorWorkspaceKind,
  type PlatformConnectorWorkspaceMode,
  type PlatformQrLoginPollResult,
  type PlatformQrLoginSession,
} from './platformConnectorModel';

export {
  beginPlatformQrLogin,
  clearPlatformConnectorCookies,
  createPassivePlatformConnectorAdapter,
  createPlatformCompatRuntimeFromConnectorAdapter,
  getBuiltinPlatformCompatContractRegistration,
  getPlatformConnectorAuthSnapshot,
  getPlatformConnectorDefinition,
  listBuiltinPlatformCompatContractRegistrations,
  listBuiltinPlatformCompatRegistrations,
  listPlatformConnectorAdapters,
  listPlatformConnectorAuthSnapshots,
  listPlatformConnectorDefinitions,
  logoutPlatformConnector,
  pollPlatformQrLogin,
  refreshAndEmitPlatformConnectorAuthSnapshot,
  registerPlatformCompatRegistrationForConnector,
  registerPlatformConnectorRegistryInitializer,
  registerPlatformConnectorAdapter,
  subscribePlatformConnectorCompatRegistrations,
  subscribePlatformConnectorDefinitions,
  unregisterPlatformCompatRegistrationForConnector,
  unregisterPlatformConnectorAdapter,
} from './platformConnectorRegistry';
