export {
  getPlatformCompatContract,
  getPlatformCompatRegistryRecord,
  getPlatformCompatRuntimeApi,
  listPlatformCompatContracts,
  listPlatformCompatRegistryRecords,
  reconcileBuiltinPlatformCompatRegistrations,
  registerPlatformCompatContract,
  subscribePlatformCompatContracts,
  subscribePlatformCompatRegistry,
  unregisterPlatformCompatContract,
  type PlatformCompatRegistryRecord,
  type RegisterPlatformCompatContractInput,
} from './contractRegistry';

export {
  getPlatformInstance,
  listPlatformInstances,
  refreshPlatformInstance,
  removePlatformInstance,
  subscribePlatformInstances,
  upsertPlatformInstance,
} from './instanceRegistry';

export {
  beginPlatformInstanceQrLogin,
  clearPlatformInstanceAuthCookies,
  getPlatformInstanceAuthSnapshot,
  listPlatformInstanceAuthSnapshots,
  logoutPlatformInstance,
  pollPlatformInstanceQrLogin,
  refreshPlatformInstanceAuthSnapshot,
  resolvePlatformInstanceId,
  type PlatformInstanceAuthSnapshot,
  type PlatformInstanceQrLoginPollResult,
  type PlatformInstanceQrLoginSession,
} from './platformInstanceAuth';

export {
  createPlatformImportedInstanceId,
  ensurePlatformImportedInstanceForInstallation,
  getPlatformImportedInstanceRecord,
  getPlatformImportedInstanceRecordByInstallationId,
  listPlatformImportedInstanceRecords,
  removePlatformImportedInstanceRecord,
  removePlatformImportedInstanceRecordByInstallationId,
  subscribePlatformImportedInstanceRecords,
  type PlatformImportedInstanceRecord,
} from './platformImportedInstanceRegistry';

export {
  getInstalledPlatformPackRecord,
  listInstalledPlatformPackRecords,
  listInstalledPlatformPackRecordsForConnector,
  loadInstalledPlatformPackRecords,
  removeInstalledPlatformPackRecord,
  subscribeInstalledPlatformPackRecords,
  type InstalledPlatformPackRecord,
  type InstalledPlatformPackSourceType,
} from './installedPlatformPacks';

export {
  clearInstalledPlatformPackCaches,
  resetInstalledPlatformPackState,
  unregisterInstalledPlatformPack,
} from './platformPackMaintenance';

export {
  getPlatformRenderSelection,
  inspectPlatformRenderSelectionPersistence,
  listPlatformRenderSelections,
  removePlatformRenderSelection,
  setPlatformRenderSelectionMounted,
  subscribePlatformRenderSelections,
  upsertPlatformRenderSelection,
  type PlatformRenderSelectionPersistenceInspection,
} from './renderSelectionRegistry';

export {
  BILIBILI_CONNECTOR_ID,
  NETEASE_CONNECTOR_ID,
  beginPlatformQrLogin,
  clearPlatformConnectorCookies,
  getPlatformConnectorAuthSnapshot,
  getPlatformConnectorDefinition,
  listPlatformConnectorAdapters,
  listPlatformConnectorDefinitions,
  listPlatformConnectorAuthSnapshots,
  logoutPlatformConnector,
  pollPlatformQrLogin,
  refreshAndEmitPlatformConnectorAuthSnapshot,
  registerPlatformConnectorAdapter,
  unregisterPlatformConnectorAdapter,
  resolvePlatformConnectorTemplate,
  createPassivePlatformConnectorAdapter,
  createPlatformCompatRuntimeFromConnectorAdapter,
  registerPlatformCompatRegistrationForConnector,
  unregisterPlatformCompatRegistrationForConnector,
  getBuiltinPlatformCompatContractRegistration,
  listBuiltinPlatformCompatRegistrations,
  subscribePlatformConnectorDefinitions,
  subscribePlatformConnectorCompatRegistrations,
  type BuiltinPlatformCompatRegistration,
  type PlatformConnectorAdapter,
  type PlatformConnectorDefinition,
  type PlatformConnectorAvailability,
  type PlatformConnectorTemplate,
  type PlatformConnectorWorkspaceKind,
  type PlatformConnectorWorkspaceMode,
  type PlatformQrLoginPollResult,
  type PlatformQrLoginSession,
  type PlatformConnectorAuthSnapshot,
  type PlatformConnectorAuthState,
  type PlatformConnectorId,
} from './connectorAuth';

export {
  awaitBuiltinPlatformPackRegistrationsReady,
  getPlatformPackStartupHealth,
  inspectBuiltinPlatformPackStoreState,
  inspectPlatformPackWorkspaceReadiness,
  inspectPlatformPackWorkspaceReadinessForInstallation,
  installPlatformPackFromFile,
  installPlatformPackFromZipBytes,
  listBuiltinPlatformPackAssets,
  listPlatformPackReadinessDiagnostics,
  listPlatformPackRegistrations,
  listPlatformPackWorkspaceSurfaces,
  removePlatformPackRegistration,
  resolvePlatformPackWorkspaceSurface,
  resolvePlatformPackWorkspaceSurfaceForInstallation,
  resolvePlatformPackWorkspaceSurfaceForInstance,
  subscribePlatformPackStartupHealth,
  subscribePlatformPackRegistrations,
  type BuiltinPlatformPackAssetDefinition,
  type BuiltinPlatformPackStoreInspection,
  type BuiltinPlatformPackStoreInspectionEntry,
  type PlatformPackBootStage,
  type PlatformPackInstallResult,
  type PlatformPackReadinessDiagnostic,
  type PlatformPackReadinessDiagnosticPhase,
  type PlatformPackReadinessDiagnosticSeverity,
  type PlatformPackRegistrationRecord,
  type PlatformPackWorkspaceReadiness,
  type PlatformPackWorkspaceReadinessDiagnostic,
  type PlatformPackStartupHealth,
  type PlatformPackStartupStageRecord,
  type PlatformPackStartupState,
} from './platformPackRegistry';

export type {
  PlatformPackWorkspaceSurfaceRecord,
} from './platformWorkspaceSurface';

export {
  listPlatformRuntimeDescriptors,
  resolvePlatformWorkspaceRoutingForConnector,
  resolvePlatformWorkspaceRoutingForInstanceId,
  resolveDefaultPlatformInstanceIdForConnector,
  resolvePlatformRuntimeDescriptorByInstanceId,
  resolvePreferredPlatformRuntimeDescriptorForConnector,
  type PlatformRuntimeDescriptor,
  type PlatformRuntimeWorkspaceMount,
  type PlatformRuntimeWorkspaceMountResolutionSource,
  type PlatformRuntimeWorkspaceRouting,
} from './platformRuntimeDescriptor';

export {
  inspectPlatformPackDoctor,
  type PlatformPackDoctorConnectorReport,
  type PlatformPackDoctorInstanceWorkspaceMountStatus,
  type PlatformPackDoctorInstallationReport,
  type PlatformPackDoctorFlowStatus,
  type PlatformPackDoctorInstanceReport,
  type PlatformPackDoctorIssue,
  type PlatformPackDoctorReport,
  type PlatformPackDoctorRenderSelectionStatus,
  type PlatformPackDoctorResolvedAssetStatus,
  type PlatformPackDoctorRuntimeBucket,
  type PlatformPackDoctorRuntimeBucketCoverage,
  type PlatformPackDoctorSeverity,
  type PlatformPackDoctorStatus,
  type PlatformPackDoctorWorkspaceSurfaceStatus,
} from './platformPackDoctor';

export {
  createDefaultPlatformLoginRegistry,
  persistPlatformLoginRegistry,
  readPlatformLoginRegistry,
  removePlatformLoginRegistryEntry,
  sanitizePlatformLoginRegistry,
  setPlatformLoginRegistryEntryEnabled,
  subscribePlatformLoginRegistry,
  upsertPlatformLoginRegistryEntry,
  type PlatformLoginRegistryEntry,
} from './platformLoginRegistry';

export {
  pickMusicPlatformGlobalCacheDirectory,
} from './cacheDirectoryPicker';

export {
  getMusicPlatformGlobalCacheSettings,
  getDefaultMusicPlatformWorkspaceOwnershipSettings,
  persistMusicPlatformWorkspaceOwnershipSettings,
  readMusicPlatformWorkspaceOwnershipSettings,
  resolveMusicPlatformWorkspaceOwnershipMode,
  setMusicPlatformConnectorWorkspaceOwnershipMode,
  setMusicPlatformGlobalCacheSettings,
  subscribeMusicPlatformWorkspaceOwnershipSettings,
  MUSIC_PLATFORM_WORKSPACE_OWNERSHIP_MODES,
  type MusicPlatformGlobalCacheSettings,
  type MusicPlatformWorkspaceOwnershipMode,
  type MusicPlatformWorkspaceOwnershipSettings,
} from './globalSettings';

export {
  clearBilibiliFacadeCaches,
  createDefaultBilibiliPlaybackQualityOptions,
  buildBilibiliPreparedResourceKey,
  buildBilibiliResourceIdentity,
  buildBilibiliSearchSourceId,
  extractBilibiliBvid,
  isBilibiliVideoSourceLocator,
  listBilibiliFavoriteFolders,
  listBilibiliFavoriteResources,
  listBilibiliRecommendedResources,
  mergeBilibiliPlaybackQualityOptions,
  normalizeBilibiliPlaybackQualityKey,
  normalizeBilibiliLookupInput,
  parseBilibiliSearchSourceId,
  resolveBilibiliQualityBadges,
  searchBilibiliResources,
  listBilibiliPlaybackQualities,
  prepareBilibiliCachedPlayback,
  resolveBilibiliCoverAssetUrl,
  resolveBilibiliWebUrl,
  resolveBilibiliLyricLocator,
  searchBilibiliResourceByBvid,
  type BilibiliFavoriteFolderItem,
  type BilibiliFavoriteResourceItem,
  type BilibiliFavoriteResourcePage,
  type BilibiliPreparedPlayback,
  type BilibiliPlaybackQualityOption,
  type BilibiliPlaybackQualityKey,
  type BilibiliQualityBadge,
  type BilibiliLyricLocatorResolved,
} from './bilibiliFacade';

export {
  clearNeteaseFacadeCaches,
  listNeteasePlaylistTracks,
  listNeteaseRecommendedPlaylists,
  listNeteaseRecommendedSongs,
  listNeteaseUserPlaylists,
  prepareNeteaseCachedPlayback,
  searchNeteaseSongs,
  type NeteasePreparedPlayback,
  type NeteaseRecommendedPlaylistItem,
  type NeteaseSongItem,
  type NeteaseSongPage,
  type NeteaseUserPlaylistItem,
} from './neteaseFacade';

export {
  listPlatformConnectorFacadeItems,
  preparePlatformPlayback,
  searchPlatformTracks,
  type PlatformPreparedPlayback,
  type PlatformConnectorFacadeItem,
  type PreparePlatformPlaybackOptions,
  type PreparePlatformPlaybackResult,
  type PlatformTrackSearchOptions,
  type PlatformTrackSearchResult,
} from './platformFacade';

export {
  clonePlatformWorkspaceCollectionItem,
  clonePlatformWorkspaceCollectionItems,
  clonePlatformWorkspacePageItem,
  clonePlatformWorkspacePageModel,
  clonePlatformWorkspacePreparedPlayback,
  clonePlatformWorkspaceQualityOption,
  clonePlatformWorkspaceQualityState,
  clonePlatformWorkspaceResourceItem,
  clonePlatformWorkspaceResourcePage,
  listPlatformWorkspaceCollections,
  listPlatformWorkspaceCollectionResources,
  createPlatformWorkspaceFeatureFlags,
  createPlatformWorkspacePageModel,
  getPlatformWorkspacePageModel,
  listPlatformWorkspaceRecommendedCollections,
  listPlatformWorkspaceRecommendedResources,
  listPlatformWorkspacePages,
  searchPlatformWorkspaceResources,
  resolvePlatformWorkspaceResource,
  preparePlatformWorkspacePlayback,
  listPlatformWorkspaceQualityState,
  listPlatformWorkspaceQualityOptions,
  setPlatformWorkspaceQualityPreference,
  resolvePlatformWorkspaceLyricLocator,
  resolvePlatformWorkspaceCoverAssetUrl,
  type PlatformWorkspaceCollectionItem,
  type PlatformWorkspaceResourceItem,
  type PlatformWorkspaceResourcePage,
  type PlatformWorkspacePreparedPlayback,
  type PlatformWorkspaceQualityState,
  type PlatformWorkspaceQualityOption,
  type PlatformWorkspaceLyricLocatorResolved,
  type PlatformWorkspaceFeatureFlags,
  type PlatformWorkspacePageItem,
  type PlatformWorkspacePageListResult,
  type PlatformWorkspacePageModel,
} from './platformWorkspaceFacade';

export type {
  PlatformApiResult,
  PlatformCompatContractFile,
  PlatformCompatRuntimeApi,
  PlatformInstanceRecord,
  PlatformRenderSelectionRecord,
} from '@pixel-matrix/plugin-platform-contracts';
