export {
  beginPlatformQrLogin,
  beginBilibiliQrLogin,
  emitPlatformConnectorAuthChanged,
  getPlatformConnectorAuthSnapshot,
  getBilibiliConnectorAuthSnapshot,
  getPlatformConnectorDefinition,
  listPlatformConnectorAdapters,
  listPlatformConnectorDefinitions,
  listPlatformConnectorAuthSnapshots,
  logoutPlatformConnector,
  logoutBilibiliConnector,
  pollPlatformQrLogin,
  pollBilibiliQrLogin,
  refreshAndEmitPlatformConnectorAuthSnapshot,
  refreshAndEmitBilibiliConnectorAuthSnapshot,
  registerPlatformConnectorAdapter,
  subscribePlatformConnectorAuthChanged,
  PLATFORM_CONNECTOR_AUTH_CHANGED_EVENT,
  type PlatformConnectorAdapter,
  type PlatformConnectorDefinition,
  type PlatformConnectorAvailability,
  type PlatformConnectorWorkspaceKind,
  type PlatformConnectorWorkspaceMode,
  type PlatformQrLoginPollResult,
  type PlatformQrLoginSession,
  type BilibiliQrLoginPollResult,
  type BilibiliQrLoginSession,
  type NeteaseQrLoginPollResult,
  type NeteaseQrLoginSession,
  type PlatformConnectorAuthSnapshot,
  type PlatformConnectorAuthState,
  type PlatformConnectorId,
} from './connectorAuth';

export {
  getBilibiliPlaybackCacheSettings,
  listBilibiliFavoriteFolders,
  listBilibiliFavoriteResources,
  listBilibiliRecommendedResources,
  searchBilibiliResources,
  listBilibiliPlaybackQualities,
  pickBilibiliCacheDirectory,
  prepareBilibiliCachedPlayback,
  resolveBilibiliCoverAssetUrl,
  resolveBilibiliLyricLocator,
  setBilibiliPlaybackCacheSettings,
  searchBilibiliResourceByBvid,
  type BilibiliPlaybackCacheSettings,
  type BilibiliFavoriteFolderItem,
  type BilibiliFavoriteResourceItem,
  type BilibiliFavoriteResourcePage,
  type BilibiliPreparedPlayback,
  type BilibiliPlaybackQualityOption,
  type BilibiliLyricLocatorResolved,
} from './bilibiliFacade';

export {
  clearNeteaseFacadeCaches,
  listNeteasePlaylistTracks,
  listNeteaseRecommendedPlaylists,
  listNeteaseRecommendedSongs,
  listNeteaseUserPlaylists,
  prepareNeteaseCachedPlayback,
  searchNeteaseSongs,
  type NeteasePreparedPlayback,
  type NeteaseRecommendedPlaylistItem,
  type NeteaseSongItem,
  type NeteaseSongPage,
  type NeteaseUserPlaylistItem,
} from './neteaseFacade';

export {
  listPlatformConnectorFacadeItems,
  searchPlatformTracks,
  type PlatformConnectorFacadeItem,
  type PlatformTrackSearchOptions,
  type PlatformTrackSearchResult,
} from './platformFacade';
