use serde::Serialize;
use std::collections::HashSet;

pub const APP_COMMAND_NAMES: &[&str] = &[
    "greet",
    "app_request_exit",
    "app_restart",
    "app_consume_pending_host_file_opens",
];

pub const DEBUG_COMMAND_NAMES: &[&str] = &[
    "debug_get_config",
    "debug_set_config",
    "debug_get_env_snapshot",
    "debug_get_startup_runtime_state",
    "debug_get_recent_git_commits",
    "debug_get_editor_windows_state",
    "governance_destroy_hidden_editor_windows",
    "governance_destroy_hidden_plugin_windows",
    "governance_destroy_hidden_vst_manager_windows",
    "debug_get_process_perf_snapshot",
    "debug_get_process_perf_totals",
    "debug_trim_process_working_set",
    "debug_get_backend_modules",
    "debug_get_registered_commands",
    "debug_telemetry_get_status",
    "debug_telemetry_ingest_batch",
    "debug_telemetry_clear_session",
    "debug_telemetry_read_current_session",
    "debug_telemetry_get_recent",
    "debug_telemetry_query",
    "debug_telemetry_export_bundle",
];

pub const MEDIA_COMMAND_NAMES: &[&str] = &["background_import_media"];

pub const PACK_COMMAND_NAMES: &[&str] = &["pack_parse_pmps_pack_bytes"];

pub const PLUGIN_COMMAND_NAMES: &[&str] = &[
    "plugin_read_install_source",
    "plugin_verify_runtime_artifact_integrity",
    "plugin_allow_dev_project_asset_scope",
    "plugin_host_capability_preflight",
    "plugin_sidecar_bridge_open",
    "plugin_sidecar_bridge_send",
    "plugin_sidecar_bridge_close",
];

pub const WINDOW_COMMAND_NAMES: &[&str] = &[
    "open_editor_window",
    "close_editor_window",
    "close_all_editor_windows",
    "open_plugin_window",
    "close_plugin_window",
    "open_plugin_shell_surface",
    "dismiss_plugin_shell_surface",
    "destroy_plugin_shell_surface",
    "open_vst_manager_window",
    "close_vst_manager_window",
    "set_editor_blur_enabled",
    "set_editor_memory_first_enabled",
    "open_workbench_native_surface",
    "sync_workbench_native_surfaces_geometry",
    "update_workbench_native_surface_content",
    "close_workbench_native_surface",
    "close_all_workbench_native_surfaces",
    "ornaments_editor_overlay_open",
    "ornaments_editor_overlay_close",
    "ornaments_render_overlay_open",
    "ornaments_render_overlay_sync_planes",
    "ornaments_overlay_sync_geometry",
    "ornaments_drag_main_window",
    "taskbar_thumbbar_sync_playback_state",
    "desktop_lyrics_set_visible",
    "desktop_lyrics_toggle_visible",
    "desktop_lyrics_set_click_through",
    "desktop_lyrics_set_font_size",
    "desktop_lyrics_set_position_preset",
    "desktop_lyrics_set_opacity_percent",
    "desktop_lyrics_set_position_offset",
    "desktop_lyrics_set_region_size",
    "desktop_lyrics_set_layout",
    "desktop_lyrics_preview_layout",
    "desktop_lyrics_commit_current_layout",
    "desktop_lyrics_set_lyric_offset_ms",
    "desktop_lyrics_import_font",
    "desktop_lyrics_debug_set_text",
    "desktop_lyrics_overlay_get_snapshot",
];

pub const LIBRARY_COMMAND_NAMES: &[&str] = &[
    "music_library_scan",
    "music_library_parse_local_track_metadata",
    "music_library_cover_lease",
    "music_library_cover_touch",
    "music_library_cover_release",
    "music_library_cover_get_lease_stats",
    "music_library_open_in_file_manager",
    "music_library_cancel_scan",
    "music_library_sync_get_status",
    "music_library_sync_run_tick",
    "music_library_sync_scheduler_get_status",
    "music_library_sync_scheduler_start",
    "music_library_sync_scheduler_stop",
    "music_library_sync_get_failure_overview",
    "music_library_sync_retry_failed_sources",
    "music_library_sync_clear_failed_sources",
    "music_library_db_upsert_source",
    "music_library_db_list_sources",
    "music_library_db_list_connectors",
    "music_library_db_list_connector_accounts",
    "music_library_lyrics_resolve",
    "music_library_lyrics_get_selected",
    "music_library_lyrics_write_back",
    "music_library_db_remove_source",
    "music_library_db_sync_tracks",
    "music_library_db_clear_tracks",
    "music_library_db_delete_tracks",
    "music_library_db_mark_track_played",
    "music_library_db_upsert_user_entry",
    "music_library_db_list_user_entries",
    "music_library_db_delete_user_entry",
    "music_library_db_mark_user_entry_played",
    "music_library_db_upsert_stable_entry_source",
    "music_library_db_list_stable_entry_sources",
    "music_library_db_delete_stable_entry_source",
    "music_library_db_upsert_playlist",
    "music_library_db_list_playlists",
    "music_library_db_delete_playlist",
    "music_library_db_touch_playlist_opened",
    "music_library_db_replace_playlist_items",
    "music_library_db_list_playlist_items",
    "music_library_db_prepend_playlist_item",
    "music_library_db_remove_playlist_item_at",
    "music_library_db_clear_playlist_items",
    "music_library_db_query_playlist_tracks_page",
    "music_library_db_upsert_fallback_task",
    "music_library_db_list_fallback_tasks",
    "music_library_db_update_fallback_task_status",
    "music_library_db_upsert_cloud_hash_job",
    "music_library_db_list_cloud_hash_jobs",
    "music_library_db_update_cloud_hash_job_status",
    "music_library_db_list_source_health",
    "music_library_db_cleanup_source_tracks",
    "music_library_db_query_tracks",
    "music_library_db_query_tracks_page",
    "music_library_db_resolve_local_playback_candidate",
    "music_library_db_list_track_field_catalog",
    "music_library_db_list_facet_catalog",
    "music_library_db_get_schema_envelope",
    "music_library_db_notify_schema_changed",
    "music_library_db_list_text_facet_values",
    "music_library_db_list_facet_entries",
    "music_library_db_list_artists",
    "music_library_db_list_genres",
    "music_library_db_list_albums",
    "music_library_db_get_stats",
];

pub const MUSIC_TAG_COMMAND_NAMES: &[&str] = &[
    "music_tag_read_local_tags",
    "music_tag_preview_db_patch",
    "music_tag_apply_db_patch",
    "music_tag_search_candidates",
];

pub const AUDIO_COMMAND_NAMES: &[&str] = &[
    "native_audio_load",
    "native_audio_analyze_peak_rms",
    "native_audio_load_source",
    "native_audio_load_and_play",
    "native_audio_load_and_play_source",
    "native_audio_play",
    "native_audio_crossfade_to",
    "native_audio_pause",
    "native_audio_stop",
    "native_audio_mark_seek_seq",
    "native_audio_record_stability_hint",
    "native_audio_seek",
    "native_audio_set_volume",
    "native_audio_set_mute",
    "native_audio_set_gain",
    "native_audio_set_replay_gain",
    "native_audio_set_dynamic_gain_enabled",
    "native_audio_set_dsp_chain",
    "native_audio_list_output_backends",
    "native_audio_select_output_backend",
    "native_audio_list_audio_inputs",
    "native_audio_select_audio_input",
    "native_audio_decoder_sidecar_describe_provider",
    "native_audio_decoder_sidecar_probe",
    "native_audio_decoder_sidecar_open_session",
    "native_audio_decoder_sidecar_close_session",
    "native_audio_decoder_sidecar_health",
    "native_audio_get_audio_components_state",
    "native_audio_get_streaming_buffer_settings",
    "native_audio_set_streaming_buffer_settings",
    "native_audio_set_spectrum_enabled",
    "native_audio_get_engine_policy",
    "native_audio_set_engine_policy",
    "native_audio_list_devices",
    "native_audio_list_devices_v2",
    "native_audio_select_device",
    "native_audio_open_asio_control_panel",
    "native_audio_append_queue",
    "native_audio_clear_queue",
    "native_audio_remove_queue_item",
    "native_audio_move_queue_item",
    "native_audio_replace_queue_item_path",
    "native_audio_sync_queue_index",
    "native_audio_load_queue_index",
    "native_audio_load_and_play_queue_index",
    "native_audio_crossfade_to_queue_index",
];

pub const DSP_COMMAND_NAMES: &[&str] =
    &["native_audio_get_dsp_graph", "native_audio_set_dsp_graph"];

pub const VST_COMMAND_NAMES: &[&str] = &[
    "native_audio_vst_list_plugins",
    "native_audio_vst_describe_plugin",
    "native_audio_vst_library_list_plugins",
    "native_audio_vst_library_get_plugin_params",
    "native_audio_vst_library_reset_plugin_scan_status",
    "native_audio_vst_library_invalidate_plugin_params_cache",
    "native_audio_vst_library_list_scan_runs",
    "native_audio_vst_library_list_scan_events",
    "native_audio_vst_library_get_scan_run_summary",
    "native_audio_vst_scan_paths_exist",
    "native_audio_vst_scan_start",
    "native_audio_vst_scan_cancel",
    "native_audio_vst_scan_state",
    "native_audio_vst_list_session_statuses",
    "native_audio_vst_set_enabled",
    "native_audio_vst_warmup",
    "native_audio_vst_open_native_editor",
    "native_audio_vst_close_native_editor",
    "native_audio_vst_bring_editors_to_front",
    "native_audio_vst_set_params",
    "native_audio_vst_set_param_value",
    "native_audio_vst_get_params",
    "native_audio_vst_dispose_session",
    "native_audio_vst_get_settings",
    "native_audio_vst_set_settings",
    "native_audio_vst_get_compatibility",
    "native_audio_vst_set_compat_rule",
    "native_audio_vst_clear_compat_rule",
    "native_audio_vst_list_presets",
    "native_audio_vst_save_preset",
    "native_audio_vst_delete_preset",
    "native_audio_vst_apply_preset",
    "native_audio_vst_get_locked_params",
    "native_audio_vst_set_param_locked",
    "native_audio_vst_get_audit_log",
    "native_audio_vst_clear_audit_log",
    "native_audio_vst_get_governance",
    "native_audio_vst_disable_plugin",
    "native_audio_vst_enable_plugin",
];

pub const MAGNET_LAYOUT_COMMAND_NAMES: &[&str] = &[
    "magnet_layout_store_get_state",
    "magnet_layout_store_bootstrap",
    "magnet_layout_store_apply_patch",
];

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CommandDomainCatalogEntry {
    pub domain: &'static str,
    pub commands: &'static [&'static str],
}

pub fn list_command_catalog() -> Vec<CommandDomainCatalogEntry> {
    vec![
        CommandDomainCatalogEntry {
            domain: "app",
            commands: APP_COMMAND_NAMES,
        },
        CommandDomainCatalogEntry {
            domain: "debug",
            commands: DEBUG_COMMAND_NAMES,
        },
        CommandDomainCatalogEntry {
            domain: "media",
            commands: MEDIA_COMMAND_NAMES,
        },
        CommandDomainCatalogEntry {
            domain: "pack",
            commands: PACK_COMMAND_NAMES,
        },
        CommandDomainCatalogEntry {
            domain: "plugins",
            commands: PLUGIN_COMMAND_NAMES,
        },
        CommandDomainCatalogEntry {
            domain: "windows",
            commands: WINDOW_COMMAND_NAMES,
        },
        CommandDomainCatalogEntry {
            domain: "library",
            commands: LIBRARY_COMMAND_NAMES,
        },
        CommandDomainCatalogEntry {
            domain: "music-tag",
            commands: MUSIC_TAG_COMMAND_NAMES,
        },
        CommandDomainCatalogEntry {
            domain: "audio",
            commands: AUDIO_COMMAND_NAMES,
        },
        CommandDomainCatalogEntry {
            domain: "dsp",
            commands: DSP_COMMAND_NAMES,
        },
        CommandDomainCatalogEntry {
            domain: "vst",
            commands: VST_COMMAND_NAMES,
        },
        CommandDomainCatalogEntry {
            domain: "magnet-layout",
            commands: MAGNET_LAYOUT_COMMAND_NAMES,
        },
    ]
}

pub fn list_registered_command_names() -> Vec<&'static str> {
    let mut commands = Vec::new();
    for entry in list_command_catalog() {
        commands.extend_from_slice(entry.commands);
    }
    commands
}

pub fn registered_command_set() -> HashSet<&'static str> {
    list_registered_command_names().into_iter().collect()
}

#[cfg_attr(not(test), allow(dead_code))]
pub fn has_duplicate_commands() -> bool {
    let commands = list_registered_command_names();
    let unique = registered_command_set();
    commands.len() != unique.len()
}

#[macro_export]
macro_rules! pmp_generate_handler {
    () => {
        tauri::generate_handler![
            crate::commands::app::greet,
            crate::commands::app::app_request_exit,
            crate::commands::app::app_restart,
            crate::commands::app::app_consume_pending_host_file_opens,
            crate::commands::debug::debug_get_config,
            crate::commands::debug::debug_set_config,
            crate::commands::debug::debug_get_env_snapshot,
            crate::commands::debug::debug_get_startup_runtime_state,
            crate::commands::debug::debug_get_recent_git_commits,
            crate::commands::debug::debug_get_editor_windows_state,
            crate::commands::debug::governance_destroy_hidden_editor_windows,
            crate::commands::debug::governance_destroy_hidden_plugin_windows,
            crate::commands::debug::governance_destroy_hidden_vst_manager_windows,
            crate::commands::debug::debug_get_process_perf_snapshot,
            crate::commands::debug::debug_get_process_perf_totals,
            crate::commands::debug::debug_trim_process_working_set,
            crate::commands::debug::debug_get_backend_modules,
            crate::commands::debug::debug_get_registered_commands,
            crate::commands::debug::debug_telemetry_get_status,
            crate::commands::debug::debug_telemetry_ingest_batch,
            crate::commands::debug::debug_telemetry_clear_session,
            crate::commands::debug::debug_telemetry_read_current_session,
            crate::commands::debug::debug_telemetry_get_recent,
            crate::commands::debug::debug_telemetry_query,
            crate::commands::debug::debug_telemetry_export_bundle,
            crate::commands::media::background_import_media,
            crate::commands::pack::pack_parse_pmps_pack_bytes,
            crate::commands::plugins::plugin_read_install_source,
            crate::commands::plugins::plugin_verify_runtime_artifact_integrity,
            crate::commands::plugins::plugin_allow_dev_project_asset_scope,
            crate::commands::plugins::plugin_host_capability_preflight,
            crate::commands::plugins::plugin_sidecar_bridge_open,
            crate::commands::plugins::plugin_sidecar_bridge_send,
            crate::commands::plugins::plugin_sidecar_bridge_close,
            crate::commands::windows::open_editor_window,
            crate::commands::windows::close_editor_window,
            crate::commands::windows::close_all_editor_windows,
            crate::commands::windows::open_plugin_window,
            crate::commands::windows::close_plugin_window,
            crate::commands::windows::open_plugin_shell_surface,
            crate::commands::windows::dismiss_plugin_shell_surface,
            crate::commands::windows::destroy_plugin_shell_surface,
            crate::commands::windows::open_vst_manager_window,
            crate::commands::windows::close_vst_manager_window,
            crate::commands::windows::set_editor_blur_enabled,
            crate::commands::windows::set_editor_memory_first_enabled,
            crate::commands::windows::open_workbench_native_surface,
            crate::commands::windows::sync_workbench_native_surfaces_geometry,
            crate::commands::windows::update_workbench_native_surface_content,
            crate::commands::windows::close_workbench_native_surface,
            crate::commands::windows::close_all_workbench_native_surfaces,
            crate::commands::windows::ornaments_editor_overlay_open,
            crate::commands::windows::ornaments_editor_overlay_close,
            crate::commands::windows::ornaments_render_overlay_open,
            crate::commands::windows::ornaments_render_overlay_sync_planes,
            crate::commands::windows::ornaments_overlay_sync_geometry,
            crate::commands::windows::ornaments_drag_main_window,
            crate::commands::windows::taskbar_thumbbar_sync_playback_state,
            crate::commands::windows::desktop_lyrics_set_visible,
            crate::commands::windows::desktop_lyrics_toggle_visible,
            crate::commands::windows::desktop_lyrics_set_click_through,
            crate::commands::windows::desktop_lyrics_set_font_size,
            crate::commands::windows::desktop_lyrics_set_position_preset,
            crate::commands::windows::desktop_lyrics_set_opacity_percent,
            crate::commands::windows::desktop_lyrics_set_position_offset,
            crate::commands::windows::desktop_lyrics_set_region_size,
            crate::commands::windows::desktop_lyrics_set_layout,
            crate::commands::windows::desktop_lyrics_preview_layout,
            crate::commands::windows::desktop_lyrics_commit_current_layout,
            crate::commands::windows::desktop_lyrics_set_lyric_offset_ms,
            crate::commands::windows::desktop_lyrics_import_font,
            crate::commands::windows::desktop_lyrics_debug_set_text,
            crate::commands::windows::desktop_lyrics_overlay_get_snapshot,
            crate::commands::library::music_library_scan,
            crate::commands::library::music_library_parse_local_track_metadata,
            crate::commands::library::music_library_cover_lease,
            crate::commands::library::music_library_cover_touch,
            crate::commands::library::music_library_cover_release,
            crate::commands::library::music_library_cover_get_lease_stats,
            crate::commands::library::music_library_open_in_file_manager,
            crate::commands::library::music_library_cancel_scan,
            crate::commands::library::music_library_sync_get_status,
            crate::commands::library::music_library_sync_run_tick,
            crate::commands::library::music_library_sync_scheduler_get_status,
            crate::commands::library::music_library_sync_scheduler_start,
            crate::commands::library::music_library_sync_scheduler_stop,
            crate::commands::library::music_library_sync_get_failure_overview,
            crate::commands::library::music_library_sync_retry_failed_sources,
            crate::commands::library::music_library_sync_clear_failed_sources,
            crate::commands::library::music_library_db_upsert_source,
            crate::commands::library::music_library_db_list_sources,
            crate::commands::library::music_library_db_list_connectors,
            crate::commands::library::music_library_db_list_connector_accounts,
            crate::commands::library::music_library_lyrics_resolve,
            crate::commands::library::music_library_lyrics_get_selected,
            crate::commands::library::music_library_lyrics_write_back,
            crate::commands::library::music_library_db_remove_source,
            crate::commands::library::music_library_db_sync_tracks,
            crate::commands::library::music_library_db_clear_tracks,
            crate::commands::library::music_library_db_delete_tracks,
            crate::commands::library::music_library_db_mark_track_played,
            crate::commands::library::music_library_db_upsert_user_entry,
            crate::commands::library::music_library_db_list_user_entries,
            crate::commands::library::music_library_db_delete_user_entry,
            crate::commands::library::music_library_db_mark_user_entry_played,
            crate::commands::library::music_library_db_upsert_stable_entry_source,
            crate::commands::library::music_library_db_list_stable_entry_sources,
            crate::commands::library::music_library_db_delete_stable_entry_source,
            crate::commands::library::music_library_db_upsert_playlist,
            crate::commands::library::music_library_db_list_playlists,
            crate::commands::library::music_library_db_delete_playlist,
            crate::commands::library::music_library_db_touch_playlist_opened,
            crate::commands::library::music_library_db_replace_playlist_items,
            crate::commands::library::music_library_db_list_playlist_items,
            crate::commands::library::music_library_db_prepend_playlist_item,
            crate::commands::library::music_library_db_remove_playlist_item_at,
            crate::commands::library::music_library_db_clear_playlist_items,
            crate::commands::library::music_library_db_query_playlist_tracks_page,
            crate::commands::library::music_library_db_upsert_fallback_task,
            crate::commands::library::music_library_db_list_fallback_tasks,
            crate::commands::library::music_library_db_update_fallback_task_status,
            crate::commands::library::music_library_db_upsert_cloud_hash_job,
            crate::commands::library::music_library_db_list_cloud_hash_jobs,
            crate::commands::library::music_library_db_update_cloud_hash_job_status,
            crate::commands::library::music_library_db_list_source_health,
            crate::commands::library::music_library_db_cleanup_source_tracks,
            crate::commands::library::music_library_db_query_tracks,
            crate::commands::library::music_library_db_query_tracks_page,
            crate::commands::library::music_library_db_resolve_local_playback_candidate,
            crate::commands::library::music_library_db_list_track_field_catalog,
            crate::commands::library::music_library_db_list_facet_catalog,
            crate::commands::library::music_library_db_get_schema_envelope,
            crate::commands::library::music_library_db_notify_schema_changed,
            crate::commands::library::music_library_db_list_text_facet_values,
            crate::commands::library::music_library_db_list_facet_entries,
            crate::commands::library::music_library_db_list_artists,
            crate::commands::library::music_library_db_list_genres,
            crate::commands::library::music_library_db_list_albums,
            crate::commands::library::music_library_db_get_stats,
            crate::commands::music_tag::music_tag_read_local_tags,
            crate::commands::music_tag::music_tag_preview_db_patch,
            crate::commands::music_tag::music_tag_apply_db_patch,
            crate::commands::music_tag::music_tag_search_candidates,
            crate::commands::audio::native_audio_load,
            crate::commands::audio::native_audio_analyze_peak_rms,
            crate::commands::audio::native_audio_load_source,
            crate::commands::audio::native_audio_load_and_play,
            crate::commands::audio::native_audio_load_and_play_source,
            crate::commands::audio::native_audio_play,
            crate::commands::audio::native_audio_crossfade_to,
            crate::commands::audio::native_audio_pause,
            crate::commands::audio::native_audio_stop,
            crate::commands::audio::native_audio_mark_seek_seq,
            crate::commands::audio::native_audio_record_stability_hint,
            crate::commands::audio::native_audio_seek,
            crate::commands::audio::native_audio_set_volume,
            crate::commands::audio::native_audio_set_mute,
            crate::commands::audio::native_audio_set_gain,
            crate::commands::audio::native_audio_set_replay_gain,
            crate::commands::audio::native_audio_set_dynamic_gain_enabled,
            crate::commands::audio::native_audio_set_dsp_chain,
            crate::commands::dsp::native_audio_get_dsp_graph,
            crate::commands::dsp::native_audio_set_dsp_graph,
            crate::commands::vst::native_audio_vst_list_plugins,
            crate::commands::vst::native_audio_vst_describe_plugin,
            crate::commands::vst::native_audio_vst_library_list_plugins,
            crate::commands::vst::native_audio_vst_library_get_plugin_params,
            crate::commands::vst::native_audio_vst_library_reset_plugin_scan_status,
            crate::commands::vst::native_audio_vst_library_invalidate_plugin_params_cache,
            crate::commands::vst::native_audio_vst_library_list_scan_runs,
            crate::commands::vst::native_audio_vst_library_list_scan_events,
            crate::commands::vst::native_audio_vst_library_get_scan_run_summary,
            crate::commands::vst::native_audio_vst_scan_paths_exist,
            crate::commands::vst::native_audio_vst_scan_start,
            crate::commands::vst::native_audio_vst_scan_cancel,
            crate::commands::vst::native_audio_vst_scan_state,
            crate::commands::vst::native_audio_vst_list_session_statuses,
            crate::commands::vst::native_audio_vst_set_enabled,
            crate::commands::vst::native_audio_vst_warmup,
            crate::commands::vst::native_audio_vst_open_native_editor,
            crate::commands::vst::native_audio_vst_close_native_editor,
            crate::commands::vst::native_audio_vst_bring_editors_to_front,
            crate::commands::vst::native_audio_vst_set_params,
            crate::commands::vst::native_audio_vst_set_param_value,
            crate::commands::vst::native_audio_vst_get_params,
            crate::commands::vst::native_audio_vst_dispose_session,
            crate::commands::vst::native_audio_vst_get_settings,
            crate::commands::vst::native_audio_vst_set_settings,
            crate::commands::vst::native_audio_vst_get_compatibility,
            crate::commands::vst::native_audio_vst_set_compat_rule,
            crate::commands::vst::native_audio_vst_clear_compat_rule,
            crate::commands::vst::native_audio_vst_list_presets,
            crate::commands::vst::native_audio_vst_save_preset,
            crate::commands::vst::native_audio_vst_delete_preset,
            crate::commands::vst::native_audio_vst_apply_preset,
            crate::commands::vst::native_audio_vst_get_locked_params,
            crate::commands::vst::native_audio_vst_set_param_locked,
            crate::commands::vst::native_audio_vst_get_audit_log,
            crate::commands::vst::native_audio_vst_clear_audit_log,
            crate::commands::vst::native_audio_vst_get_governance,
            crate::commands::vst::native_audio_vst_disable_plugin,
            crate::commands::vst::native_audio_vst_enable_plugin,
            crate::commands::audio::native_audio_list_output_backends,
            crate::commands::audio::native_audio_select_output_backend,
            crate::commands::audio::native_audio_list_audio_inputs,
            crate::commands::audio::native_audio_select_audio_input,
            crate::commands::audio::native_audio_decoder_sidecar_describe_provider,
            crate::commands::audio::native_audio_decoder_sidecar_probe,
            crate::commands::audio::native_audio_decoder_sidecar_open_session,
            crate::commands::audio::native_audio_decoder_sidecar_close_session,
            crate::commands::audio::native_audio_decoder_sidecar_health,
            crate::commands::audio::native_audio_get_audio_components_state,
            crate::commands::audio::native_audio_get_streaming_buffer_settings,
            crate::commands::audio::native_audio_set_streaming_buffer_settings,
            crate::commands::audio::native_audio_set_spectrum_enabled,
            crate::commands::audio::native_audio_get_engine_policy,
            crate::commands::audio::native_audio_set_engine_policy,
            crate::commands::audio::native_audio_list_devices,
            crate::commands::audio::native_audio_list_devices_v2,
            crate::commands::audio::native_audio_select_device,
            crate::commands::audio::native_audio_open_asio_control_panel,
            crate::commands::audio::native_audio_append_queue,
            crate::commands::audio::native_audio_clear_queue,
            crate::commands::audio::native_audio_remove_queue_item,
            crate::commands::audio::native_audio_move_queue_item,
            crate::commands::audio::native_audio_replace_queue_item_path,
            crate::commands::audio::native_audio_sync_queue_index,
            crate::commands::audio::native_audio_load_queue_index,
            crate::commands::audio::native_audio_load_and_play_queue_index,
            crate::commands::audio::native_audio_crossfade_to_queue_index,
            crate::magnet_layout_store::magnet_layout_store_get_state,
            crate::magnet_layout_store::magnet_layout_store_bootstrap,
            crate::magnet_layout_store::magnet_layout_store_apply_patch
        ]
    };
}

#[cfg(test)]
mod tests {
    use super::has_duplicate_commands;

    #[test]
    fn command_registry_has_no_duplicates() {
        assert!(!has_duplicate_commands());
    }
}
