export type CapabilityPermission = `api:${string}` | `storage:${string}` | `net:${string}` | string;

export type {
  CancelRequest,
  CapabilityId,
  CapabilityInvokeRequest,
  CapabilityInvokeResponse,
  CapabilityInvokeResponseError,
  CapabilityInvokeResponseOk,
  CapabilityProtocolMessage,
  CapabilityProvision,
  CapabilityRequirement,
  DataPlaneKind,
  DisposeRequest,
  HandleId,
  LeaseId,
  ProtocolError,
  ProtocolVersion,
  PxpEnvelopeBase,
  RequestId,
  ResourceDurabilityScope,
  ResourceHandleDescriptor,
  SessionCloseRequest,
  SessionCloseResponse,
  SessionCloseResponseError,
  SessionCloseResponseOk,
  SessionId,
  SessionOpenRequest,
  SessionOpenResponse,
  SessionOpenResponseError,
  SessionOpenResponseOk,
  StreamCredit,
  StreamData,
  StreamEnd,
  StreamId,
  StreamOpenRequest,
  StreamOpenResponse,
  StreamOpenResponseError,
  StreamOpenResponseOk,
} from './core';
